trigger: none

resources:
  repositories:
    - repository: templates
      name: "Factory U/cicd"
      ref: "refs/tags/1.11.1"
      trigger: none
      type: git

variables:
  # Variables
  buildConfiguration: "Release"

  # Condition
  isPR: ${{ startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}

extends:
  template: templates/nuget-pipelines.yml@templates
  parameters:
    image: dotnet_sdk_jre:8.0.0
    sonarqube:
      enabled: false
    build:
      publish: ${{ eq(variables.isPR, false) }}
      steps:
      - task: Assembly-Info-NetCore@3
        inputs:
          Path: "$(Build.SourcesDirectory)"
          FileNames: "src/*/*.csproj"
          InsertAttributes: false
          FileEncoding: "auto"
          WriteBOM: false
          VersionNumber: "$(Build.BuildNumber)"
          FileVersionNumber: "$(Build.BuildNumber)"
          LogLevel: "verbose"
          FailOnWarning: false
          DisableTelemetry: false

      - task: DotNetCoreCLI@2
        displayName: Restore Project
        inputs:
          command: "restore"
          projects: "src/*/*.csproj"
          feedsToUse: "select"
  
      - task: DotNetCoreCLI@2
        displayName: Build The Project
        inputs:
          command: "build"
          projects: "src/*/*.csproj"
          arguments: "--configuration $(BuildConfiguration)"
 
      - task: DotNetCoreCLI@2
        displayName: Execute Unit Tests
        enabled: true
        inputs:
          command: "test"
          projects: "**/*[Tt]ests/*.csproj"
          arguments: "--configuration $(BuildConfiguration)"

    release:
      sln: .dev/Orano.CreateSolution/Orano.CreateSolution/.csproj 
      configuration: $(BuildConfiguration)
      feedPublish: 'factoryu'
      nupkg: '**/*.nupkg'