# Application configuration
config:
  appName: myproject-user

secret:
  secretProviderClass: ns-dev-myproject-vault-secrets

imagePullSecrets:
- name: fc-oay-dev-myproject-registry-secret-01

serviceAccountName: dev-myproject-sa

service:
  containerPort: 80

ingress:
  enabled: true
  hosts: 
  - host: myproject-api.orano.cloud
    paths:
      - path: /
        pathType: Prefix